language: php

sudo: false

addons:
    postgresql: "9.4"

services:
    - elasticsearch
    - postgresql

php:
    - 5.5
    - 5.6
    - 7.0

matrix:
    fast_finish: true

before_install:
    - phpenv config-rm xdebug.ini || true
    - composer self-update

install:
    - composer install --prefer-source

before_script:
    - sleep 10 # wait for elasticsearch to start and be available
    - curl -sSL https://raw.githubusercontent.com/moliware/travis-solr/master/travis-solr.sh | SOLR_VERSION=4.10.4 SOLR_CONFS="./scripts/solr/config/conf/schema.xml ./scripts/solr/config/conf/solrconfig.xml" bash

script:
    - make databases
    - make tests
